### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/ros-gazebo-gym-ws#29]
**TODOS:**
- [x] Rended sphinx documentation
- [x] Create sphinx documentation pages
- [x] Add python version to the readme.
- [x] Update README.md
