### ISSUE TITLE
Move to using ROS Noetic

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/ros-gazebo-gym-ws#39]
It would be nice if we move to ROS Noetic to get rid of the very extensive [install instructions](https://rickstaa.github.io/gazebo-panda-gym/get_started/install.html). There are however some packages that still are blocking this transition.

### ROS noetic transition list
- [ ] [franka_ros](https://github.com/frankaemika/franka_ros)
    - [x] franka_control
    - [x] franka_description  
    - [ ] franka_example_controllers - Depends on panda_moveit_config which is not released yet (see [franka_ros/issues/123](https://github.com/frankaemika/franka_ros/issues/123))
    - [x] franka_gripper
    - [x] franka_hw 
    - [x] franka_msgs
    - [ ] [franka_ros](https://github.com/frankaemika/franka_ros) - Also depends on panda_moveit_config which is not released yet (see [franka_ros/issues/123](https://github.com/frankaemika/franka_ros/issues/123))
    - [x] franka_visualization 
- [ ] gazebo_panda_gym - Compatible with ROS noetic if end effector control is removed. 
- [x] Openai_ros - Can be removed as it was only added as a reference.
- [ ] [panda_moveit_config](https://github.com/ros-planning/panda_moveit_config/issues/77) - Not yet compatible with ROS noetic (see [panda_moveit_config/issues/77](https://github.com/ros-planning/panda_moveit_config/issues/77). ❌ 
- [ ] panda_openai_sim - Should be compatible with ROS Noetic when we do the following:
    - [ ] Remove the end effector control. This needs to be done since this requires the 
- [ ] panda_simulation - Should be compatible with ROS Noetic when we do the following:
    - [ ] Remove the end effector control. Because it depends on  [panda_moveit_config](https://github.com/ros-planning/panda_moveit_config/issues/77).
    - [ ] Move from [tf](https://wiki.ros.org/tf) to [tf2](https://wiki.ros.org/tf2).
- [x] panda_training - No problem already written in python3
- [x] theconstruct_msgs - Compatible with noetic. We however could get rid of this package and add the message to our own package #38.
